### ISSUE TITLE
IPFS Station Setup

### ISSUE THREAD

**Issue by dignifiedquire** [MrChrisJ/fullnode#22]
So this is what I did this morning from the fresh image you sent me.
1. Copy image using `dd` and expand on the pi
2. Setup wifi using this [guide](http://www.howtogeek.com/167425/how-to-setup-wi-fi-on-your-raspberry-pi-via-the-command-line/)
3. Install [nvm](https://github.com/creationix/nvm#install-script) with `curl`
4. Restart shell
5. Install node:
   
   ``` bash
   $ nvm install 5
   $ npm install -g npm # Latest npm 
   ```
6. Install station
   
   ``` bash
   $ git clone https://github.com/ipfs/station.git
   $ cd station
   $ npm install
   $ npm start
   ```

**Comment by MrChrisJ** [comment]
This is fantastic, I just remade a new version of the Fullnode OS and [we're looking good](https://twitter.com/MrChrisEllis/status/714559319400923142). I think I must have had a dodgy internet connection before. Danke schön.  

And feel free to add it to the [Setup Guides](https://github.com/MrChrisJ/fullnode/tree/master/Setup_Guides) folder if you want. Otherwise I will add it on the next round of updates.
